name: Git mirror
description: Mirrors the current git repository to a target location
inputs:
  target-git-url:
    description: Target git url
    required: true
  ssh-private-key:
    description: SSH private key for git auth
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Add ssh key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: Add known host keys
      shell: bash
      run: |
        ssh-keyscan git.sr.ht >> ~/.ssh/known_hosts

    - name: Push to target mirror
      shell: bash
      run: |
        git remote add target ${{ inputs.target-git-url }}
        git push --force target --tags "refs/remotes/origin/*:refs/heads/*"
