name: Git mirror
description: Mirrors the current git repository to a target location
inputs:
  target-git-url:
    description: Target git url
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Push to target mirror
      shell: bash
      run: |
        git remote add target ${{ inputs.target-git-url }}
        git push --force target --tags "refs/remotes/origin/*:refs/heads/*"
